apiVersion: v1
kind: Pod
spec:
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
      - name: my-ssh-keyfile
        mountPath: /home/.ssh/id_rsa
    volumes:
      - name: config-volume
        configMap:
          name: special-config
      - name: my-ssh-keyfile
        secret:
          name: my-secret