apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      role: mongo
      environment: test
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      containers:
      - name: mongo
        image: gcr.io/total-earth-365910/mongo:latest
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: my-claim
      spec:
        storageClassName: slow
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
